### ISSUE TITLE
Find a REST API which returns random words or phrases in English or Russian language

### ISSUE THREAD

**Issue by anatoly-scherbakov** [anatoly-scherbakov/geopatterns-demo#1]
The REST API should accept GET requests with no authorization, and return one or a few random words per request.

This API will be triggered by the front end, the user will be able to click the phrase to input it into the search field.

List the APIs found in comments to this issue.

**Comment by RomanZorkin** [comment]
Below is a list of resources that provide a randomly generated word or phrase on request.

1. This resource allows you to get a random word on request https://random-words-api.vercel.app/word
The answer will be in the form:

```json
[
  {
    "word": "Numinous",
    "definition": "Of, like or pertaining to a deity; suffused with religious awe  ",
    "pronunciation": "Numinous"
  }
]
```

Resource - https://github.com/mcnaveen/Random-Words-API

2. This resource allows you to get a random phrase https://fish-text.ru/get?format=json&number=1
The answer will be in the form:

```json
{"status":"success","text":"phrase....."}
```

Request format rule in the source - https://fish-text.ru/api

3. You can bild your own service, based on "loremipsum" python module https://pypi.org/project/loremipsum/#files

Example main.py:

```python
from fastapi import FastAPI

from lorem_ipsum import text_generator
app = FastAPI()

@app.get("/")
def read_root():
    return {text_generator()}
```

Example lorem_ipsum.py

```python
from loremipsum import Generator


def text_generator():
    paragraph = Generator()
   return paragraph.generate_sentence()[2]
```

4. My amazon lambda https://q8gkoni0w8.execute-api.us-east-2.amazonaws.com/firs_stage

**Comment by RomanZorkin** [comment]
`from loremipsum import Generator


def text_generator():
paragraph = Generator()
return paragraph.generate_sentence()[2]`

**Comment by anatoly-scherbakov** [comment]
@RomanZorkin thanks for the research!

If you want to contribute the FastAPI powered random text generator to this project, I would be looking forward to merge it. Issue is: #9.

This issue is getting closed.
