### ISSUE TITLE
Use `loremipsum` endpoint to generate the random text

### ISSUE THREAD

**Issue by anatoly-scherbakov** [anatoly-scherbakov/geopatterns-demo#22]
Right now, there is a little discrepancy in the functioning of the app.

1. The app has a https://dqrura49d0.execute-api.us-east-1.amazonaws.com/random-phrase endpoint, which retruns a random phrase in Latin,
2. but the front end is not using that endpoint — instead it calls https://fish-text.ru

That

- We have built a piece of functionality with `loremipsum` that we're not using;
- fish-text.ru provides texts in Russian. That's ok but a project like this — an educational project for beginners in Python & cloud computing — is international. That's why we're writing all our comments, pull requests, and issues in English: thus, whoever wants from any part of the world — be it Russia, Europe, China, India, Brazil or Iceland — may come and join us in writing code.

That being said, please switch the front end to use our own `random-phrase` API endpoint instead of fish-text.ru.

**Comment by RomanZorkin** [comment]
Yes, of course, this was an intermediate option until the random_phrase endpoint appeared in the main branch. I forgot to note this flaw in the pull request. The adjustment is already in progress.
