### ISSUE TITLE
Use an English vocabulary to generate random phrases

### ISSUE THREAD

**Issue by anatoly-scherbakov** [anatoly-scherbakov/geopatterns-demo#23]
Depends on #22.

The `/random-phrase` endpoint currently generates a random phrase in Latin. Like this:

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quamquam te quidem video minime esse deterritum. Hic nihil fuit, quod quaereremus. Facile est hoc cernere in primis puerorum aetatulis. Quo modo autem philosophus loquitur? Id enim natura desiderat. Duo Reges: constructio interrete.

This is too long for our screen. I think that on the screen of the demo app perhaps max 3 words can fit — more will go over the screen size. And it is also not funny — a dull Lorem Ipsum text everyone has seen hundreds of times.

Can we generate something ourselves?

For example, we could have a list of adjectives:

- funny
- green
- hard
- nerdy
- wild
- …

and a list of nouns:

- programming
- Python
- clouds
- code
- …

and then create phrases from these like:

- green clouds
- nerdy kangaroo
- furry Python

whatever. Any other ideas are welcome.

When done, I also suggest to write a unit test to cover this function. This unit test might check that the output string contains two words separated by a space, for example.

**Comment by RomanZorkin** [comment]
It,s realy funny & very good idea!!! In work:)
